Theta* algo now able to be chosen for pathfinding
aliaksei135/seedpod_ground_risk pull request #40
Opened 2021-06-24 16:06 UTC by Zach10a

Implemented the Theta Star algorithm into the menu of the pathfinding layer. In the picture below the Theta Star is in green and the A* is in megenta. This may require a slight tweak as all other factors were the same.

![image](https://user-images.githubusercontent.com/35232913/123296053-34619180-d50e-11eb-96e6-ea48a5f8948a.png)

2021-06-24 20:31 UTC, aliaksei135 commented
Theta* doesn't seem to like non-smooth costmaps. I would stick to using it only on risk maps (see #39 ). 

Please refactor the changed algo name (`RiskThetaStar` -> `GridThetaStar`) properly. I haven't checked all the references to it, but I can see the corresponding tests haven't been refactored!

2021-06-25 16:29 UTC, Zach10a commented
That should now work and everything has been refactored

2021-07-01 16:06 UTC, Zach10a commented
Bump

2021-07-01 16:36 UTC, aliaksei135 requested changes

2021-07-01 16:36 UTC, aliaksei135 commented on seedpod_ground_risk/pathfinding/theta_star.py
> +class GridThetaStar(Algorithm):
This class doesn't get used anywhere and does not abstract any functionality, so is useless

2021-07-01 16:47 UTC, merged