Fix graph regen
aliaksei135/seedpod_ground_risk pull request #66
Opened 2021-09-15 10:19 UTC by Zach10a

This PR adds more URLs for the program to try upon one of them not responding correctly. It also now displays a message to the user giving them the error that has occurred and asking them to regenerate the plot. 

It should be noted that something has happened recently which means that the SSL certificate was throwing errors when trying to access the Overpass API. Until I figure out how we can fix this the varify flag has been set to False. As no secure data is being transmitted this should be ok for now, however, if we have to start using API keys then this needs to be fixed.

2021-09-15 14:55 UTC, aliaksei135 requested changes

2021-09-15 14:55 UTC, aliaksei135 commented on seedpod_ground_risk/layers/osm_tag_layer.py
> +    overpass_urls = ["https://overpass.kumi.systems/api/interpreter", "https://lz4.overpass-api.de/api/interpreter",
Why not add all the [global instances](https://wiki.openstreetmap.org/wiki/Overpass_API#Public_Overpass_API_instances)? Also `kumi` endpoint is in here twice.

2021-09-15 14:55 UTC, aliaksei135 commented on seedpod_ground_risk/layers/strike_risk_layer.py
> +                 ac: dict = AIRCRAFT_LIST['Default'],
Changes unrelated to PR

2021-09-15 14:55 UTC, aliaksei135 commented on static_data/aircraft_list.json
> +    "failure_prob": 0.01
Changes unrelated to PR

2021-09-15 14:55 UTC, aliaksei135 commented on seedpod_ground_risk/layers/osm_tag_layer.py
> +requests.packages.urllib3.disable_warnings(InsecureRequestWarning)
Add a TODO and a comment here explaining why for down the line when we inevitably forget

2021-09-15 14:57 UTC, aliaksei135 commented
CI tests also fail due to a `FileNotFoundError`. This doesn't seem related to any OSM query problems...

2021-09-16 10:45 UTC, Zach10a commented
So this PR now cycles through all of the global instances allowed by Overpass. It appears something has changed with their system that sometimes causes issues with connection, however, when this happens the user is now given the error and promoted to regenerate. I'll keep looking to find the change that's happened with the API.

2021-09-16 11:15 UTC, aliaksei135 commented
Have you tried reverting to something like v0.11.0 and seeing if the same problem exists? If that works I suggest a `git bisect` would be in order :)

2021-09-16 11:28 UTC, Zach10a commented
Tried releases all the way back to v0.11.0, fairly sure this is an issue with the Overpass servers.Seen a couple of comments online saying they are quite busy.

2021-09-28 19:50 UTC, Zach10a commented
It appears changing it from a GET request to a POST request has worked. The comment with this research (from @aliaksei135 ) is pasted below in case the other methods of fixing these errors need to be tried in the future.

***Okay so I have done a bit more research on this. Here are a few things to try:

Send as POST requests instead of GET, like we are doing now
Set a meaningful User-Agent header, something like seedpod-ground-risk v0.13.0 (Python 3.8/requests v<xxx>;)
Set the Content-Type header to what it actually is: application/x-www-form-urlencoded; charset=UTF-8
***

2021-09-28 20:19 UTC, Zach10a commented
Changed headers as requested

2021-09-28 20:39 UTC, aliaksei135 requested changes

2021-09-28 20:39 UTC, aliaksei135 commented on seedpod_ground_risk/layers/osm_tag_layer.py
> +    headers = {'User-Agent': 'seedpod-ground-risk v0.13.0 (Python 3.8/requests v2.25.1;)',
Set the versions programmatically eg `requests.__version__` instead of hard coding then having to up date every release!

2021-09-29 13:58 UTC, Zach10a commented
This is ready to rumble, merging sooner rather than later would be ideal!

2021-09-29 22:05 UTC, aliaksei135 approved these changes
Now that CI passes this looks cracking

2021-09-29 22:05 UTC, merged